server:
  port: 10243

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/DataCenter}
